apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: A Streamlit microservice
  tags:
    - streamlit
    - python
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
