apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: Streamlit app scaffolded via Backstage
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
