apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}
  template:
    metadata:
      labels:
        app: ${{ values.name }}
    spec:
      containers:
        - name: ${{ values.name }}
          image: your-dockerhub-username/${{ values.name }}:latest
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}-service
spec:
  selector:
    app: ${{ values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
